credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: hashed_password  # Replace with a hashed password

cookie:
  expiry_days: 30
  key: some_random_key
  name: streamlit_auth

key: some_secret_key
